### PR TITLE
MapSwipe change detection article - New image

### PR DESCRIPTION
**Pull request by imbaah**
Hi,

I am a bit lost to be honest. I hope I am doing this right: I'd like to add **Missing Maps blog article banner 2** to the missing maps img file so I can change the potato quality of the current banner to that one. 

Thank you for your understanding.

### CODE REVIEW

**Comment by danbjoseph** [comment]
the image used for the preview on https://www.missingmaps.org/blog/ and the image used at the top of the page with the blog post itself will both be the same. what image do you want to use for that?

**Comment by imbaah** [comment]
I'd like to change the current banner with the new single image called banner2 please. I will change the URL on the text file along with some font sizes (and make a request ofc) but wanted to add the banner2 image to the missing maps img file first since that's what I'm supposed to do in order to have a URL? Am I making sense? This is like speaking a new language to me, sorry for being slow in understanding and explaining.



Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by danbjoseph** [comment]
to change the banner, you should replace the current banner image file so that there is not an orphan image file in the repo that isn't used on the page. i can walk you through it tomorrow if you'd like.

also, for the URLs, if you know the filename you can know what the URL will be. they will all follow the same format of
`https://raw.githubusercontent.com/MissingMaps/img/main/images/my_file_name.jpg`

**Comment by imbaah** [comment]
Thank you for explaining these to me! Yes I'd love for you to walk me through it but FYI I am still planning on using the original "banner" image in the article.

My name on Slack is Lale Pirlot. I am on Istanbul time but any time works for me really.


________________________________

**Comment by danbjoseph** [comment]
after syncing your fork, this PR properly shows only 1 file added or changed.

**Pull request merged**
